language: node_js
node_js:
  - "12"
services:
  - docker
install:
  - npm install
script:
  - npm test
  - docker build . -t personal-site-client:latest
after_success:
  - docker tag personal-site-client:latest davidtjohn/personal-site-client:latest
  -  #!/bin/bash
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push davidtjohn/personal-site-client:latest
before_deploy:
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
after_deploy:
