language: node_js
node_js:
  - "12"
services:
  - docker
install:
  - npm install
script:
  - npm test
  - docker build . -t personal-site-client:latest
after_success:
  - docker tag personal-site-client:latest davidtjohn/personal-site-client:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push davidtjohn/personal-site-client:latest
before_deploy:
  # - pip install --user awscli
  # - export PATH=$PATH:$HOME/.local/bin
  # - eval $(aws ecr get-login-password --region us-east-2)
  # - docker tag personal-site-client:latest 117645150012.dkr.ecr.us-east-2.amazonaws.com/personal-site-client:latest
  # - docker push 117645150012.dkr.ecr.us-east-2.amazonaws.com/personal-site-client:latest
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
after_deploy:
  - echo "Deployment was successful!"
