language: node_js
node_js:
  - "12"
services:
  - docker
script:
  - docker build . -t davidtjohn/personal-site-client:latest
  - docker push davidtjohn/personal-site-client:latest davidtjohn/personal-site-client:latest
